name: warranzy_demo
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bottom_navy_bar: ^5.1.0
  # onesignal: ^1.1.0

  flutter_localizations:
      sdk: flutter
  cupertino_icons: ^0.1.2
  extended_image: ^0.5.1
  flutter_speed_dial: ^1.2.1
  shared_preferences: ^0.5.3+2
  simple_animations: ^1.3.0
  flutter_form_builder: ^3.0.1
  sqflite: ^1.1.5
  uuid: ^2.0.1
  get_it: ^1.0.3+1
  local_auth: ^0.4.0+1
  keyboard_actions: "^1.0.3"
  country_code_picker: ^1.1.5
  # barcode_scan: ^1.0.0
  # url_launcher: ^5.0.2
  image_picker: ^0.6.0+8
  flutter_slidable: "^0.4.9"
  path_provider: ^1.1.0
  bloc: ^0.10.0
  flutter_bloc: ^0.8.0
  equatable: ^0.2.0
  shimmer: ^1.0.0
  sliver_fab: ^1.0.0 
  page_transition: ^1.1.0
  carousel_slider: ^1.3.0
  flutter_swiper: ^1.1.6 
  flutter_image_compress: ^0.5.1
  provider: ^3.0.0+1
  flutter_launcher_icons: "^0.7.0"
  rflutter_alert: ^1.0.2
  fancy_bottom_navigation: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/warranzy_logo_new.jpg"

flutter:

  uses-material-design: true

  assets:
   - locale/i18n_en.json
   - locale/i18n_la.json
   - locale/i18n_th.json

   - assets/icons/ 
   - assets/images/
   - assets/logo/

  fonts:
    - family: Supermarket
      fonts:
        - asset: assets/fonts/supermarket.ttf
          weight: 800          
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Ekkamai
      fonts:
        - asset: assets/fonts/EkkamaiStandard-Light.ttf
        # - asset: fonts/TrajanPro_Bold.ttf
          weight: 700
