name: warranzy_demo
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cached_network_image: ^1.1.1
  auto_size_text: ^2.1.0
  connectivity: ^0.4.5+3

  onesignal: ^1.1.0
  intl: ^0.15.8
  badges: ^1.1.0
  url_launcher: ^5.1.0
  flutter_credit_card: ^0.1.1
  country_pickers: ^1.1.0
  extended_image: ^0.5.7
  http: 0.12.0+2
  shared_preferences: ^0.5.3+2
  simple_animations: ^1.3.0
  flutter_form_builder: ^3.0.1
  sqflite: ^1.1.5
  get_it: ^1.0.3+1
  local_auth: ^0.4.0+1
  keyboard_actions: "^1.0.3"
  barcode_scan: ^1.0.0
  image_picker: ^0.6.0+8
  flutter_slidable: "^0.4.9"
  path_provider: ^1.1.0
  sliver_fab: ^1.0.0
  page_transition: ^1.1.0
  carousel_slider: ^1.3.0
  flutter_image_compress: ^0.6.3
  provider: ^3.0.0+1
  flutter_launcher_icons: "^0.7.0"
  flutter_picker: ^1.0.13
  device_info: ^0.4.0+2
  pin_code_text_field: ^1.3.7
  dio: ^2.1.13
  flutter_native_timezone: ^1.0.4
  cloud_firestore: ^0.12.9
  autocomplete_textfield: ^1.7.3
  jaguar_jwt: ^2.1.6
  global_configuration: ^1.2.0
  progress_indicators: ^0.1.4
  keyboard_avoider: ^0.1.2
  # firebase_messaging: ^5.1.6
  # gallery_saver: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/warranzy_logo_new.jpg"

flutter:
  uses-material-design: true

  assets:
    - locale/i18n_en.json
    - locale/i18n_la.json
    - locale/i18n_th.json

    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/cfg/
    - assets/icons/avatars/
    - assets/icons/icons_category/

  fonts:
    - family: Supermarket
      fonts:
        - asset: assets/fonts/supermarket.ttf
          weight: 800
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: Ekkamai
      fonts:
        - asset: assets/fonts/EkkamaiStandard-Light.ttf
          # - asset: fonts/TrajanPro_Bold.ttf
          weight: 700
